server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.10.200.99:3100/loki/api/v1/push

scrape_configs:
- job_name: varlogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: weblogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: weblogs
      __path__: /Null/logs/*log